In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/insurance.csv')
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

# CODIFICACIÓN DE VARIABLE CATEGORIA SMOKER

In [6]:
df_encoded = pd.get_dummies(df,columns=["smoker"],drop_first=True)
df_encoded['smoker_yes'] = df_encoded['smoker_yes'].astype(int)
df_encoded.dtypes

age             int64
sex            object
bmi           float64
children        int64
region         object
charges       float64
smoker_yes      int64
dtype: object

In [7]:
X = df_encoded[['smoker_yes','age','bmi']]
y = df_encoded['charges']

#ENTRENAMIENTO DEL MODELO

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor
import sklearn.metrics as metrics

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = SGDRegressor(max_iter=1000,learning_rate='optimal',random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

#erro cuadratico medio
mse = metrics.mean_squared_error(y_test,y_pred)
#R2 Coeficiente de determinación
r2 = metrics.r2_score(y_test,y_pred)

print(f'El error cuadratico medio(MSE) es de {round(mse,4)}')
print(f'El coeficiente de determinación(R2) es de {round(r2,4)}')

El error cuadratico medio(MSE) es de 43270721.7829
El coeficiente de determinación(R2) es de 0.7213

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

scaler_y = StandardScaler()
y_train = scaler_y.fit_transform(y_train.values.reshape(-1,1)).ravel()
y_test = scaler_y.fit_transform(y_test.values.reshape(-1,1)).ravel()

model = SGDRegressor(max_iter=1000,learning_rate='optimal',random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)


y_pred_original = scaler_y.inverse_transform(y_pred.reshape(-1,1)).ravel()
y_test_original = scaler_y.inverse_transform(y_test.reshape(-1,1)).ravel()

#erro cuadratico medio
mse = metrics.mean_squared_error(y_test_original,y_pred_original)
#R2 Coeficiente de determinación
r2 = metrics.r2_score(y_test_original,y_pred_original)

print(f'El error cuadratico medio(MSE) es de {round(mse,4)}')
print(f'El coeficiente de determinación(R2) es de {round(r2,4)}')

El error cuadratico medio(MSE) es de 46060281.3644
El coeficiente de determinación(R2) es de 0.7033