In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
titanic_df = sns.load_dataset('titanic')
titanic_df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

# EDA

In [3]:
titanic_df.dtypes.value_counts()

object      5
int64       4
float64     2
bool        2
category    1
category    1
Name: count, dtype: int64

In [4]:
titanic_df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
columns_to_drop = ['fare','embarked','class','who','adult_male','deck','embark_town','alive','alone']
titanic_df.drop(columns_to_drop,axis='columns',inplace=True)
titanic_df

KeyError: "['fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone'] not found in axis"

In [7]:
titanic_df.shape

(891, 6)

In [8]:
titanic_df.dropna()

     survived  pclass     sex   age  sibsp  parch
0           0       3    male  22.0      1      0
1           1       1  female  38.0      1      0
2           1       3  female  26.0      0      0
3           1       1  female  35.0      1      0
4           0       3    male  35.0      0      0
..        ...     ...     ...   ...    ...    ...
885         0       3  female  39.0      0      5
886         0       2    male  27.0      0      0
887         1       1  female  19.0      0      0
889         1       1    male  26.0      0      0
890         0       3    male  32.0      0      0

[714 rows x 6 columns]

#CODIFICACIÓN DE VARIABLES CATEGORICAS

In [9]:
titanic_df.dtypes

survived      int64
pclass        int64
sex          object
age         float64
sibsp         int64
parch         int64
dtype: object

In [10]:
titanic_df = pd.get_dummies(titanic_df,columns=['sex'],drop_first=True)
titanic_df.head()

   survived  pclass   age  sibsp  parch  sex_male
0         0       3  22.0      1      0      True
1         1       1  38.0      1      0     False
2         1       3  26.0      0      0     False
3         1       1  35.0      1      0     False
4         0       3  35.0      0      0      True

In [11]:
titanic_df['sex_male'] = titanic_df['sex_male'].astype(int)
titanic_df.rename(columns = {'sex_male':'sex'},inplace=True)
titanic_df.head(10)

   survived  pclass   age  sibsp  parch  sex
0         0       3  22.0      1      0    1
1         1       1  38.0      1      0    0
2         1       3  26.0      0      0    0
3         1       1  35.0      1      0    0
4         0       3  35.0      0      0    1
5         0       3   NaN      0      0    1
6         0       1  54.0      0      0    1
7         0       3   2.0      3      1    1
8         1       3  27.0      0      2    0
9         1       2  14.0      1      0    0

# ENTRENAMIENTO USANDO ARBOLES DE DECISIÓN

## PASO 1 - DEFINIMOS VARIABLES

In [12]:
X = titanic_df.drop("survived",axis=1)
y = titanic_df['survived']

## PASO 2 - DIVIDIMOS DATASET EN ENTRENAMIENTO Y TEST

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=00000)

## PASO 3 - CREAR EL MODELO DE ARBOL DE DECISIÓN

In [14]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()

## PASO 4 - ENTRENAMOS EL MODELO

In [15]:
tree.fit(X_train,y_train)

DecisionTreeClassifier()

# EVALUAMOS EL MODELO

In [16]:
from sklearn.metrics import accuracy_score

y_pred = tree.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)

print(f'Accuracy : {accuracy}')

Accuracy : 0.7988826815642458